import type { TrackProfile } from "./types";

export const TRACKS: TrackProfile[] = [
  {
    id: "charlotte",
    name: "Charlotte Motor Speedway",
    layout: "Oval",
    kind: "intermediate",
    lengthMi: 1.5,
    banking: "24° in 1–2, 20° in 3–4",
    typicalLaps: 80,
    gear: "4.00",
    fuelPerLap: 0.215,
    notes: "High-speed 1.5. Long-run RF is the race. Keep the splitter at ~0.25 in and don’t over-tape a green run.",
  },
  {
    id: "kansas",
    name: "Kansas Speedway",
    layout: "Oval",
    kind: "intermediate",
    lengthMi: 1.5,
    banking: "17–20°",
    typicalLaps: 80,
    gear: "3.89",
    fuelPerLap: 0.208,
    notes: "Wide, abrasive. Build a touch more cross than Charlotte so the truck doesn’t free up too early on worn rubber.",
  },
  {
    id: "vegas",
    name: "Las Vegas Motor Speedway",
    layout: "Oval",
    kind: "intermediate",
    lengthMi: 1.5,
    banking: "20°",
    typicalLaps: 80,
    gear: "3.89",
    fuelPerLap: 0.21,
    notes: "Smooth and fast. Slightly stiffer front rates and a bit more tape than Kansas. Watch water temp in traffic.",
  },
  {
    id: "texas",
    name: "Texas Motor Speedway",
    layout: "Oval",
    kind: "intermediate",
    lengthMi: 1.5,
    banking: "20–24°",
    typicalLaps: 80,
    gear: "4.00",
    fuelPerLap: 0.218,
    notes: "Progressive banking. Truck wants to push in the center — a hair more track-bar and less cross than Vegas.",
  },
  {
    id: "atlanta",
    name: "EchoPark Speedway",
    layout: "Oval",
    kind: "intermediate",
    lengthMi: 1.54,
    banking: "28°",
    typicalLaps: 80,
    gear: "3.42",
    fuelPerLap: 0.232,
    notes: "Superspeedway-style pack on an intermediate body. Lower gear, more tape caution, and a stable long-run wedge.",
  },
  {
    id: "homestead",
    name: "Homestead-Miami Speedway",
    layout: "Oval",
    kind: "intermediate",
    lengthMi: 1.5,
    banking: "18–20°",
    typicalLaps: 80,
    gear: "3.89",
    fuelPerLap: 0.205,
    notes: "Variable banking. Give the driver a lane — slightly looser mid-corner than Charlotte so you can move up.",
  },
  {
    id: "michigan",
    name: "Michigan International Speedway",
    layout: "Oval",
    kind: "speedway",
    lengthMi: 2.0,
    banking: "18°",
    typicalLaps: 80,
    gear: "3.42",
    fuelPerLap: 0.248,
    notes: "Two-mile draft track. Softer wheel rates, more rear ride, and a 12:1 steering box to save the nose.",
  },
  {
    id: "pocono",
    name: "Pocono Raceway",
    layout: "Tri-oval",
    kind: "speedway",
    lengthMi: 2.5,
    banking: "14° / 8° / 6°",
    typicalLaps: 80,
    gear: "3.42",
    fuelPerLap: 0.255,
    notes: "Three distinct corners. Compromise camber and a taller rear for the long straights. Brake bias a touch rearward.",
  },
];

export const DEFAULT_TRACK_ID = "charlotte";
